name: test
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Chrome 145 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -q "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_145.0.7360.0-1_amd64.deb" -O chrome.deb
          sudo apt-get install -y ./chrome.deb

      - name: Install Chrome 145 (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $url = "https://dl.google.com/chrome/install/145.0.7360.0/chrome_installer.exe"
          Invoke-WebRequest -Uri $url -OutFile chrome_installer.exe
          Start-Process -FilePath chrome_installer.exe -Args "/silent /install" -Wait

      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run tests
        env:
          ZENDRIVER_TEST_BROWSERS: "headless"
          ZENDRIVER_TEST_NO_SANDBOX: "true"
        shell: bash
        run: ./scripts/test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
